version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apivendas
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - '6379:6379'
    restart: always

  app:
    build: .
    container_name: app_node
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=apivendas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=123456

volumes:
  pgdata:
