version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apivendas
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_node
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=apivendas

volumes:
  pgdata:
